### PR TITLE
Update flake and fix nix dependencies

### PR DESCRIPTION
**Pull request by zachcoyle**
This fixes the flake build

### CODE REVIEW

**Comment by pipelight** [comment]
To merge asap please.

**Review by alvaro17f — APPROVED** [review]

**Comment by l4l** [comment]
Thanks!

**Comment by pipelight** [comment]
This piece of software is a game changer in my workflow. I couldn't do without or switch to rofi! Thank you very much for your reactivity.

**Comment by zachcoyle** [comment]
> Thanks!

you're welcome! :)

**Comment by zachcoyle** [comment]
@l4l I think this fixes https://github.com/l4l/yofi/issues/155 minus the scope-creep of direnv

**Pull request merged**
