### PR TITLE
Search by keywords in apps mode

### LINKED ISSUE #26: Can't launch gedit as "gedit"
Testing yofi snapshot (377497b134970347ae91a71320cf31d046342d33) from 2020-12-30. I notice that I can't launch gedit by typing "gedit". I have to type something that matches "Text Editor" instead. Is yofi only checking the `Name` entries of desktop files?

I see the `/usr/share/applications/org.gnome.gedit.desktop` file on Arch Linux has the following:

```
Keywords[en_GB]=Text;Editor;Plaintext;Write;gedit;
```

Could it be possible add support for matching these keywords?

### PR DESCRIPTION
**Pull request by l4l**
resolves #26

### CODE REVIEW

**Comment by l4l** [comment]
Locales will be addressed later in #32

**Comment by alanorth** [comment]
I'm not sure why, but this stopped working for me. I just tried latest master and I can no longer launch Gedit by typing "gedit". It worked a few months ago when I tested the `keyword-search` branch. Not sure what changed...

**Comment by l4l** [comment]
@alanorth, mind to file a separate issue? Would be helpful to see a log file (launch `yofi --verbose --log-file my.log`) and stdout/stderr output.

**Comment by alanorth** [comment]
@l4l no need to file a new issue. I tried to reproduce it with a verbose log and I cannot. Strange! Sorry for the noise.

**Pull request merged**
